package com.prime.datastructure.CommuincateInterface;

import static com.prime.datastructure.CommuincateInterface.CommandBase.CMD_ServicePlayer_PVR_Base;

public class PvrModule {
    public static final int CMD_ServicePlayer_PVR_Init = CMD_ServicePlayer_PVR_Base+0x01;
    public static final int CMD_ServicePlayer_PVR_DeInit = CMD_ServicePlayer_PVR_Base+0x02;
    public static final int CMD_ServicePlayer_PVR_RecordStart = CMD_ServicePlayer_PVR_Base+0x03;
    public static final int CMD_ServicePlayer_PVR_RecordStop = CMD_ServicePlayer_PVR_Base+0x04;
    public static final int CMD_ServicePlayer_PVR_PlayCheckLastPositionPoint = CMD_ServicePlayer_PVR_Base+0x05;
    public static final int CMD_ServicePlayer_PVR_PlayFileStart = CMD_ServicePlayer_PVR_Base+0x06;
    public static final int CMD_ServicePlayer_PVR_PlayFileStop = CMD_ServicePlayer_PVR_Base+0x07;
    public static final int CMD_ServicePlayer_PVR_PlayPlay = CMD_ServicePlayer_PVR_Base+0x08;
    public static final int CMD_ServicePlayer_PVR_PlayPause = CMD_ServicePlayer_PVR_Base+0x09;
    public static final int CMD_ServicePlayer_PVR_PlayFastForward = CMD_ServicePlayer_PVR_Base+0x0A;
    public static final int CMD_ServicePlayer_PVR_PlayRewind = CMD_ServicePlayer_PVR_Base+0x0B;
    public static final int CMD_ServicePlayer_PVR_PlayGetSpeed = CMD_ServicePlayer_PVR_Base+0x0C;
    public static final int CMD_ServicePlayer_PVR_PlayChangeAudioTrack = CMD_ServicePlayer_PVR_Base+0x0D;
    public static final int CMD_ServicePlayer_PVR_PlayGetCurrentAudioIndex = CMD_ServicePlayer_PVR_Base+0x0E;
    public static final int CMD_ServicePlayer_PVR_PlayGetPlayTime = CMD_ServicePlayer_PVR_Base+0x0F;
    public static final int CMD_ServicePlayer_PVR_PlayGetPlayStatus = CMD_ServicePlayer_PVR_Base+0x10;
    public static final int CMD_ServicePlayer_PVR_TimeShiftStart = CMD_ServicePlayer_PVR_Base+0x11;
    public static final int CMD_ServicePlayer_PVR_TimeShiftStop = CMD_ServicePlayer_PVR_Base+0x12;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayPause = CMD_ServicePlayer_PVR_Base+0x13;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayResume = CMD_ServicePlayer_PVR_Base+0x14;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayFastForward = CMD_ServicePlayer_PVR_Base+0x15;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayRewind = CMD_ServicePlayer_PVR_Base+0x16;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayGetSpeed = CMD_ServicePlayer_PVR_Base+0x17;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayChangeAudioTrack = CMD_ServicePlayer_PVR_Base+0x18;
    public static final int CMD_ServicePlayer_PVR_TimeShiftPlayGetStatus = CMD_ServicePlayer_PVR_Base+0x19;
    public static final int CMD_ServicePlayer_PVR_TimeShiftGetTimeInfo = CMD_ServicePlayer_PVR_Base+0x1A;
    public static final int CMD_ServicePlayer_PVR_GetRecCount = CMD_ServicePlayer_PVR_Base+0x1B;
    public static final int CMD_ServicePlayer_PVR_GetSeriesRecCount = CMD_ServicePlayer_PVR_Base+0x1C;
    public static final int CMD_ServicePlayer_PVR_GetRecLink = CMD_ServicePlayer_PVR_Base+0x1D;
    public static final int CMD_ServicePlayer_PVR_GetSeriesRecLink = CMD_ServicePlayer_PVR_Base+0x1E;
    public static final int CMD_ServicePlayer_PVR_DelSeriesRecs = CMD_ServicePlayer_PVR_Base+0x1F;
    public static final int CMD_ServicePlayer_PVR_DelOneRec = CMD_ServicePlayer_PVR_Base+0x20;
    public static final int CMD_ServicePlayer_PVR_CheckSeriesEpisode = CMD_ServicePlayer_PVR_Base+0x21;
    public static final int CMD_ServicePlayer_PVR_IsIdxInUse = CMD_ServicePlayer_PVR_Base+0x22;
    public static final int CMD_ServicePlayer_PVR_HddMonitorStart = CMD_ServicePlayer_PVR_Base+0x23;
    public static final int CMD_ServicePlayer_PVR_HddMonitorStop = CMD_ServicePlayer_PVR_Base+0x24;
    public static final int CMD_ServicePlayer_PVR_SetMountUsbPath = CMD_ServicePlayer_PVR_Base+0x25;
    public static final int CMD_ServicePlayer_PVR_UnmountUsbPath = CMD_ServicePlayer_PVR_Base+0x26;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_IsFullRecording = CMD_ServicePlayer_PVR_Base+0x27;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_IsTimeshiftStart = CMD_ServicePlayer_PVR_Base+0x28;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_GetRecNum = CMD_ServicePlayer_PVR_Base+0x29;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_IsChannelRecording = CMD_ServicePlayer_PVR_Base+0x2A;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_RecordStart = CMD_ServicePlayer_PVR_Base+0x2B;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_RecordStop = CMD_ServicePlayer_PVR_Base+0x2C;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_GetRecTunerId = CMD_ServicePlayer_PVR_Base+0x2D;
    public static final int CMD_ServicePlayer_PVR_GetMountUsbPath = CMD_ServicePlayer_PVR_Base+0x2E;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_PlaybackStart = CMD_ServicePlayer_PVR_Base+0x2F;
    public static final int CMD_ServicePlayer_PVR_ChangeChannelManager_PlaybackStop = CMD_ServicePlayer_PVR_Base+0x30;
    public static final int CMD_ServicePlayer_PVR_PlaySeek = CMD_ServicePlayer_PVR_Base+0x31;
    public static final int CMD_ServicePlayer_PVR_PlaySetSpeed = CMD_ServicePlayer_PVR_Base+0x32;
    public static final int CMD_ServicePlayer_PVR_DelAllRecs = CMD_ServicePlayer_PVR_Base+0x33;

    public static final String KEY_USB_MOUNT_PATH = "UsbMountPath";
    public static final String KEY_MASTER_REC_INDEX = "MasterRecIndex";
    public static final String KEY_SERIES_REC_INDEX = "SeriesRecIndex";
    public static final String KEY_FROM_LAST_POS = "FromLastPos";
    public static final String KEY_PLAY_TIME = "PlayTime";
    public static final String KEY_SEEK_MODE = "SeekMode";
    public static final String KEY_SEEK_OFFSET_SECS = "SeekOffsetSecs";
    public static final String KEY_SPEED = "Speed";
    public static final String KEY_COUNT = "Count";
    public static final String ACTION_ENABLE_SERIES_RECORDING = "com.prime.tvinputframework.ACTION_ENABLE_SERIES_RECORDING";
    public static final String ACTION_UPDATE_PROGRESS_WHILE_RECORDING = "com.prime.tvinputframework.ACTION_UPDATE_PROGRESS_WHILE_RECORDING";
}
