package com.prime.dtv.sysdata;



public enum EnDvbPsisiStreamType { // previously DVB_PSISI_STREAM_TYPE_E
    DTV_PSISI_STREAM_RESERVED(0x00),
    DTV_PSISI_STREAM_VIDEO_MPEG1(0x01),
    DTV_PSISI_STREAM_VIDEO_MPEG2(0x02),
    DTV_PSISI_STREAM_AUDIO_MPEG1(0x03),
    DTV_PSISI_STREAM_AUDIO_MPEG2(0x04),
    DTV_PSISI_STREAM_PRIVATE_SECTIONS(0x05),
    DTV_PSISI_STREAM_PRIVATE_PES(0x06),
    DTV_PSISI_STREAM_MHEG(0x07),
    DTV_PSISI_STREAM_DSM_CC(0x08),
    DTV_PSISI_STREAM_TYPE_H2221(0x09),
    DTV_PSISI_STREAM_TYPE_A(0x0A),
    DTV_PSISI_STREAM_TYPE_B(0x0B),
    DTV_PSISI_STREAM_TYPE_C(0x0C),
    DTV_PSISI_STREAM_TYPE_D(0x0D),
    DTV_PSISI_STREAM_TYPE_AUX(0x0E),
    DTV_PSISI_STREAM_AUDIO_AAC_ADTS(0x0F),
    DTV_PSISI_STREAM_VIDEO_MPEG4(0x10),
    DTV_PSISI_STREAM_AUDIO_AAC_LATM(0x11),
    DTV_PSISI_STREAM_AUDIO_AAC_RAW(0x12),
    DTV_PSISI_STREAM_VIDEO_H264(0x1B),
    DTV_PSISI_STREAM_VIDEO_AVS(0x42),
    DTV_PSISI_STREAM_AUDIO_AVS(0x43),
    DTV_PSISI_STREAM_VIDEO_WM9(0xEA),
    DTV_PSISI_STREAM_AUDIO_WM9(0xE6),
    DTV_PSISI_STREAM_AUDIO_AC3(0x81),
    DTV_PSISI_STREAM_AUDIO_DTS(0x85),
    DTV_PSISI_STREAM_AUDIO_DRA(0x90);

    private int value;

    EnDvbPsisiStreamType(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }
}
