LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_CERTIFICATE := platform
LOCAL_SDK_VERSION := current
ifneq (${LOCAL_DEVICE_RRO_OVERLAY},)
LOCAL_RESOURCE_DIR := $(LOCAL_DEVICE_RRO_OVERLAY)
else
LOCAL_RESOURCE_DIR := $(LOCAL_PATH)/res
endif
LOCAL_PACKAGE_NAME := PrimeRro_Source
#LOCAL_VENDOR_MODULE := true
LOCAL_SYSTEM_EXT_MODULE := true

include $(BUILD_RRO_PACKAGE)
